"""Generate short smoke-test configs from the real training configs.

A smoke test answers "does this model train at all?" -- not "how good is it".
Three epochs is enough to catch the failures that matter: a model that will not
build, a loss that returns NaN, an OOM at the configured batch size, a label
mapping that produces out-of-range classes, or a metric that comes back None.

Each generated config is the real one with two changes:

* ``training.epochs`` reduced (default 3)
* ``experiment.name`` / ``output_dir`` suffixed with ``_smoke``

Everything else -- data, splits, batch size, learning rate, architecture -- is
left exactly as the real run, so a smoke pass is genuine evidence the real run
will start. It says nothing about final accuracy.

Also writes matching CEI test configs, so each smoke checkpoint can be scored on
the 100 CEI tiles straight away.

Usage
-----
python tools/cei/make_smoke_configs.py
python tools/cei/make_smoke_configs.py --epochs 5
"""

import argparse
import copy
import os
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CONFIG_DIR = os.path.join(REPO_ROOT, "configs", "unet", "cei")

# (smoke experiment name, train config, matching CEI test config) per model.
#
# The smoke name is explicit rather than derived from experiment.name, because
# model 2's real run is called "cei_exp01_oem2cei" for historical reasons --
# deriving would produce "cei_exp01_oem2cei_smoke" and overwrite the earlier
# 5-epoch smoke experiment of the same name.
MODELS = [
    ("cei_m1_ftunetformer_swinb_smoke",
     "ftunetformer_swinb_oem2cei.yml", "test/test_m1_ftunetformer_cei.yml"),
    ("cei_m2_unet_effb4_smoke",
     "unet_effb4_oem2cei.yml", "test/test_m2_uneteffb4_cei.yml"),
    ("cei_m3_unetformer_r101_smoke",
     "unetformer_r101_oem2cei.yml", "test/test_m3_unetformer_cei.yml"),
    ("cei_m4_upernet_swinb_smoke",
     "upernet_swinb_oem2cei.yml", "test/test_m4_upernet_cei.yml"),
    ("cei_m5_segformer_mitb5_smoke",
     "segformer_mitb5_oem2cei.yml", "test/test_m5_segformer_cei.yml"),
]


def load(path):
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def dump(config, path, header):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(header)
        yaml.safe_dump(config, handle, sort_keys=False, default_flow_style=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--out-dir", default=os.path.join(CONFIG_DIR, "smoke"))
    args = parser.parse_args()

    written = []

    for name, train_name, test_name in MODELS:
        train_path = os.path.join(CONFIG_DIR, train_name)
        test_path = os.path.join(CONFIG_DIR, test_name)

        if not os.path.isfile(train_path):
            print(f"SKIP {train_name}: not found")
            continue

        train_config = load(train_path)
        train_config["training"]["epochs"] = args.epochs
        train_config["experiment"]["name"] = name
        train_config["experiment"]["output_dir"] = f"./experiments/{name}"

        stem = os.path.splitext(os.path.basename(train_name))[0]
        out_train = os.path.join(args.out_dir, f"{stem}_smoke.yml")
        dump(
            train_config,
            out_train,
            f"# {args.epochs}-epoch smoke test generated from {train_name}.\n"
            f"# Identical to the real config apart from epochs and output_dir.\n"
            f"# Regenerate with tools/cei/make_smoke_configs.py -- do not hand-edit.\n",
        )

        # Matching test config: same model section, CEI dataset, smoke output dir.
        if os.path.isfile(test_path):
            test_config = load(test_path)
            test_config["experiment"]["name"] = name
            test_config["experiment"]["output_dir"] = f"./experiments/{name}"
            out_test = os.path.join(args.out_dir, f"test_{stem}_smoke.yml")
            dump(
                test_config,
                out_test,
                f"# CEI test config for the {args.epochs}-epoch smoke run of {stem}.\n"
                f"# Generated by tools/cei/make_smoke_configs.py -- do not hand-edit.\n",
            )
        else:
            out_test = None
            print(f"  note: {test_name} not found, no smoke test config written")

        written.append((name, out_train, out_test))

    print(f"\nWrote {len(written)} smoke config pair(s) to {args.out_dir}\n")
    for name, train_out, test_out in written:
        print(f"  {name}")
        print(f"    train: {os.path.relpath(train_out, REPO_ROOT)}")
        if test_out:
            print(f"    test : {os.path.relpath(test_out, REPO_ROOT)}")


if __name__ == "__main__":
    main()
